---
title: "Schedule"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

| Week | Date      | Chapter | Topic                                               |                                                            Key Info                                                            |                                                                        Slides QMD                                                                        |                                                                   Slides PDF                                                                    |                                    Slides Notes                                    |                                                                                                          Exit tix                                                                                                          |                          Record-ing                           |                             Muddy Points                             |
|-------|-------|-------|-------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 1    | 9/30      |         | Welcome                                             |       [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Intro/00_Intro_key_info.qmd)]{style="color:#f8f5f0;"}       |                          [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"}                          |                  [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Intro/00_Intro.pdf)]{style="color:#f8f5f0;"}                  | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQkhZOVI1QlIyWDNCRU44MUVXME1MNTNCNy4u)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 1       | Outcomes, Events, and Sample Space                  |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |         [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Outcomes_Events_Sample/01_Outcomes_Events_Sample.qmd)]{style="color:#f8f5f0;"}         | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Outcomes_Events_Sample/01_Outcomes_Events_Sample.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 10/2      | 2       | Probability                                         | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Probability/02_Probability_key_info.qmd)]{style="color:#f8f5f0;"} |                    [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Probability/02_Probability.qmd)]{style="color:#f8f5f0;"}                    |            [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Probability/02_Probability.pdf)]{style="color:#f8f5f0;"}            | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQUlOMFlVUUFVNk9LR044TTczT0JSMzcwSy4u)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 22      | Introduction to Counting                            |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                 [[{{< iconify ri slideshow-fill size=30px >}}](lessons/22_Counting_Intro/22_Counting_Intro.qmd)]{style="color:#f8f5f0;"}                 |         [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/22_Counting_Intro/22_Counting_Intro.pdf)]{style="color:#f8f5f0;"}         | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **10/3**  |         | **HW 0 due 11pm**                                   |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 2    | 10/7      | 3       | Independent Events                                  |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |             [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Independent_Events/03_Independent_Events.qmd)]{style="color:#f8f5f0;"}             |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 4       | Conditional Probability                             |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |        [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Conditional_Probability/04_Conditional_Probability.qmd)]{style="color:#f8f5f0;"}        |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 10/9      | 5       | Bayes Theorem                                       |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                  [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Bayes_Theorem/05_Bayes_Theorem.qmd)]{style="color:#f8f5f0;"}                  |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 7       | Random Variables                                    |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |               [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_Random_Variables/07_Random_Variables.qmd)]{style="color:#f8f5f0;"}               |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **10/10** |         | **HW 1 due 11pm**                                   |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 3    | 10/14     | 8       | pmfs and CDFs                                       |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                  [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_pmfs_and_cdfs/08_pmfs_and_cdfs.qmd)]{style="color:#f8f5f0;"}                  |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 14      | Bernoulli RV                                        |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_20_Discrete_RVs/14_20_Discrete_RVs.qmd)]{style="color:#f8f5f0;"}                |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 15      | Binomial RV                                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           | 16      | Geometric RV                                        |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           | 19      | Hypergeometric RV                                   |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           | 20      | Discrete Uniform RV                                 |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | 10/16     | 17      | Negative Binomial RV                                |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_Negative_binomial_rv/17_Negative_binomial_rv.qmd)]{style="color:#f8f5f0;"}           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 18      | Poisson RV                                          |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                     [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_Poisson_rv/18_Poisson_rv.qmd)]{style="color:#f8f5f0;"}                     |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **10/17** |         | **HW 2 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **10/20** |         | **HW 1 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 4    | 10/21     | 9       | Independence and Conditioning (Joint Distributions) |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |            [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_Joint_distributions/09_Joint_distributions.qmd)]{style="color:#f8f5f0;"}            |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 10/23     | 10      | Expected Values of discrete RVs                     |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Expected_Values/10_Expected_Values.qmd)]{style="color:#f8f5f0;"}                |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **10/25** |         | **HW 3 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **10/28** |         | **HW 2 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 5    | 10/28     | 11      | Expected Values of *sums of* discrete RVs           |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Expected_Values_of_Sums_of_rvs/11_Expected_Values_of_Sums_of_rvs.qmd)]{style="color:#f8f5f0;"} |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 10/30     | 12      | Variance of discrete RVs                            |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                       [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Variance/12_Variance.qmd)]{style="color:#f8f5f0;"}                       |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **10/31** |         | **HW 4 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **11/3**  |         | **HW 3 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 6    | 11/4      | pre-24  | Calculus Review                                     |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 11/6      | 24      | Continuous RVs and PDFs                             |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **11/7**  |         | **HW 5 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | 11/8      |         | HW 3 videos due 11pm                                |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **11/10** |         | **HW 4 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 7    | 11/11     | 31      | Uniform RV                                          |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 32      | Exponential RV                                      |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 33      | Gamma RV                                            |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 35      | Normal RV                                           |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 11/13     | 25      | Joint Densities                                     |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **11/14** |         | **HW 6 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **11/17** |         | **HW 5 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 8    | 11/18     | 26      | Independent continuous RVs                          |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 27      | Conditional distributions                           |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | 11/20     | 28      | Expected value of continuous RVs                    |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **11/21** |         | **HW 7 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **11/24** |         | **HW 6 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 9    | 11/25     | 29      | Variance of continuous RVs                          |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      |           | 36      | Sums of independent normal RVs                      |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                                                                                                                                                                            | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 11/27     |         | No class                                            |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **11/27** |         | **HW 8 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **12/1**  |         | **HW 7 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 10   | 12/2      | 37      | Central limit theorem                               |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | 12/4      | 43      | Moment generating functions                         |                            [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                          [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                           |                                  [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                                   | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |                                                                     [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"}                                                                     | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|      | **12/5**  |         | **HW 9 due 11 pm**                                  |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **12/8**  |         | **HW 8 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | 12/?      |         | HW 7 presentations due 11pm                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      |           |         |                                                     |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
| 11   | 12/9      |         | Catch up day!                                       |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **12/12** |         | **Optional HW 10 due 11 pm**                        |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |
|      | **12/13** |         | **HW 9 solutions due 11pm**                         |                                                                                                                                |                                                                                                                                                          |                                                                                                                                                 |                                                                                    |                                                                                                                                                                                                                            |                                                               |                                                                      |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 46,6, 6, 6, 6, 6, 6, 6\]"}
