---
title: "Homework 3"
subtitle: "BSTA 550"
description: "Due: Thursday October 25, 2024 at 11pm"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

## Directions

[Please turn in this homework on Sakai.](https://sakai.ohsu.edu/portal/site/BSTA-550-1-14926-F24/tool/c8320b13-1b6d-42ed-9c19-134634cf25af) Please submit your homework in pdf format. You can type your work on your computer or submit a photo of your written work or any other method that can be turned into a pdf. The Adobe Scan phone app is an easy way to scan photos and compile into a PDF. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

**Try to complete all of the problems listed below at some point this quarter! You may want to save some of them for studying later!** Only turn in the ones listed in the "Turn In" column. Please submit problems in the order they are listed.

*You must show all of your work to receive credit.*

::: center
| Chapter |      Turn In       |    Extra Problems    |
|:-------:|:------------------:|:--------------------:|
|    5    | TB \# 17, NTB \# 1 |     \# 1, 9, 11      |
|    7    |                    | \# 2, 10, 16, 17, 18 |
|    8    |  TB \# 8\*, 18\*   |    \# 2, 5, 7, 10    |
:::

\* In addition to the graphs, include piecewise defined functions for the pmf and cdf.

## Non-textbook problems (NTB)

1.  A new drug is packaged to contain 30 pills in a bottle. Suppose that 98% of all bottles contain no defective pills, 1.5% contain one defective pill, and 0.5% contain two defective pills. Two pills from a bottle are randomly selected and tested. What is the probability that there are 2 defective pills in the bottle given that one of the two tested pills is defective?
