---
title: "Homework 2"
subtitle: "BSTA 550"
description: "Due: Thursday October 17, 2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

## Directions

[Please turn in this homework on Sakai.](https://sakai.ohsu.edu/portal/site/BSTA-550-1-14926-F24/tool/c8320b13-1b6d-42ed-9c19-134634cf25af) Please submit your homework in pdf format. You can type your work on your computer or submit a photo of your written work or any other method that can be turned into a pdf. The Adobe Scan phone app is an easy way to scan photos and compile into a PDF. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

**Try to complete all of the problems listed below at some point this quarter! You may want to save some of them for studying later!** Only turn in the ones listed in the "Turn In" column. Please submit problems in the order they are listed.

*You must show all of your work to receive credit.*

::: center
| Chapter |      Turn In       |              Extra Problems              |
|:-------:|:------------------:|:----------------------------------------:|
|  22\*   |      TB \# 1       | \# 3, 5, 7, 25, 27, 30, 31, 39-41, 43-48 |
|    3    | TB \# 10, NTB \# 1 |           \# 4, 9, 12, 13\*\*            |
|    4    |      TB \# 5       |             \# 1, 4, 11, 13              |
|    5    | TB \# 17, NTB \# 2 |               \# 1, 9, 11                |
:::

\* Please note the following for Chapter 22:

-   See the table on pg. 277, which summarizes some key combinatorics concepts.

-   Problems 39-48 are a set that build on one another and more advanced than the other problems. It'll be much easier to do #42 after doing 39-41.

-   I *highly* recommend reading Chapter 23, which is a series of case studies in counting: poker hands and Yahtzee.

\*\*For #3.13, mathematically solve for the sample size instead of plugging in numbers and guessing.

## Non-textbook problems (NTB)

1.  Recall from class, that we defined events $A,B,$ and $C$ to mutually independent if both (1) and (2) below hold. This point of this exercise is to show that $(1)\nRightarrow (2),$ and $(2)\nRightarrow (1).$ $$\begin{array}{cc}
        (1) & \mathbb{P}(A\cap B\cap C)=\mathbb{P}(A)\mathbb{P(}B)\mathbb{P(}C) \\ 
        (2) & \mathbb{P}(A\cap B)=\mathbb{P}(A)\mathbb{P(}B) \\ 
        & \mathbb{P}(A\cap C)=\mathbb{P}(A)\mathbb{P(}C) \\ 
        & \mathbb{P}(B\cap C)=\mathbb{P}(B)\mathbb{P(}C)%
        \end{array}%$$
    a.  Suppose two different fair dice are rolled. Let events $A,B,$ and $C$ be defined in the following way: $$\begin{array}{cl}
        A: & \text{Roll a total of 7} \\ 
        B: & \text{First die is a 6} \\ 
        C: & \text{Second die is a 2}%
        \end{array}%$$

        Show that condition $(2)$ holds, but that condition $(1)$ does not.

    b.  Suppose two different fair dice are rolled. Let events $A,B,$ and $C$ be defined in the following way: $$\begin{array}{cl}
        A: & \text{Roll a 1 or 2 on the first die} \\ 
        B: & \text{Roll a 3, 4, or 5 on the second die} \\ 
        C: & \text{Roll a total of 4, 11, or 12}%
        \end{array}%$$

        Show that condition $(1)$ holds, but that condition $(2)$ does not.
2.  A new drug is packaged to contain 30 pills in a bottle. Suppose that 98% of all bottles contain no defective pills, 1.5% contain one defective pill, and 0.5% contain two defective pills. Two pills from a bottle are randomly selected and tested. What is the probability that there are 2 defective pills in the bottle given that one of the two tested pills is defective?
