---
title: "Chapter 43: Moment Generating Functions Part 1"
author: "Meike Niederhausen and Nicky Wakim"
date: "12/3/2024"
title-slide-attributes:
    data-background-color: "#006a4e"
format: 
  revealjs:
    theme: "../simple_NW.scss"
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: Chapter 43 Slides
    html-math-method: mathjax
---

## Learning Objectives



## What are moments?

::: definition
::: def-title
Definition 1
:::
::: def-cont
The $j^{th}$ moment of a r.v. $X$ is $\mathbb{E}[X^j]$
:::
:::

## Example 

::: example
::: ex-title
Example 2
::: 
::: ex-cont
$1^{st}-4^{th}$ moments
:::
:::

## What is an *moment generating function* (mgf)??

::: definition
::: def-title
Definition 3
:::
::: def-cont
If $X$ is a r.v., then the **moment generating function**
(**mgf**) associated with $X$ is:
$$M_X(t)= \mathbb{E}[e^{tX}]$$
:::
:::

**Remarks**

::: columns
::: column
-   For a discrete r.v., the mgf of $X$ is
    $$M_X(t)= \mathbb{E}[e^{tX}]=\sum_{all \ x}e^{tx}p_X(x)$$

-   For a continuous r.v., the mgf of $X$ is
    $$M_X(t)= \mathbb{E}[e^{tX}]=\int_{-\infty}^{\infty}e^{tx}f_X(x)dx$$
:::
::: column
-   The mgf $M_X(t)$ is a function of $t$, not of $X$, and it might not
    be defined (i.e. finite) for all values of $t$. We just need it to
    be defined for $t=0$.
:::
:::

## Example 

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 4
:::
::: ex-cont
What is $M_X(t)$ for $t=0$?
:::
:::
:::
:::

## Theorem 

::: theorem
::: thm-title
Theorem 5
:::
::: thm-cont
The moment generating function uniquely specifies a probability distribution.
:::
:::

::: theorem
::: thm-title
Theorem 6
:::
::: thm-cont
$$\mathbb{E}[X^r] = M_X^{(r)}(0)$$
:::
:::

::: proof
*Proof.* ◻
:::

## Example

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 7
:::
::: ex-cont
Let $X \sim Poisson(\lambda)$

1.  Find the mgf of $X$

2.  Find $\mathbb{E}[X]$

3.  Find $Var(X)$
:::
:::
**Remark:** Finding the mean and variance is sometimes easier with the following
trick
:::
:::


## Theorem

::: theorem
::: thm-title
Theorem 8
:::
::: thm-cont
Let $R_X(t) = \ln[M_X(t)]$. Then,

$\mu = \mathbb{E}[X] = R_X'(0)$ and $\sigma^2 = Var(X) = R_X''(0)$
:::
:::


::: proof
*Proof.* ◻
:::

## Example

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 9
:::
::: ex-cont
Let $X \sim Poisson(\lambda)$.

1.  Find $\mathbb{E}[X]$ using $R_X(t)$

2.  Find $Var(X)$ using $R_X(t)$
:::
:::
:::
:::

## Example 


::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 10
:::
::: ex-cont
Let $Z$ be a standard normal random variable, i.e.
$Z \sim N(0,1)$.

1.  Find the mgf of $Z$

2.  Find $\mathbb{E}[Z]$

3.  Find $Var(Z)$
:::
:::
:::
:::
